<?php

include_once("../../config.php");
include_once($config['base']['doc_root']."/modules/base/index.php");
include_once($config['base']['doc_root']."/modules/db/index.php");
include_once($config['base']['doc_root']."/modules/themes/index.php");
include_once($config['base']['doc_root']."/libs/xmlrpc/xmlrpc.inc");
include_once($config['base']['doc_root']."/libs/xmlrpc/xmlrpc_wrappers.inc");
include_once($config['base']['doc_root']."/libs/xmlrpc/xmlrpcs.inc");
connect_2db ($db_user, $db_password, $db_host, $db_name);

	/**
	* Used to test usage of object methods in dispatch maps and in wrapper code
	*/
	class xmlrpc_server_methods_container
	{
		/**
		* Method used to test logging of php warnings generated by user functions.
		*/
		function phpwarninggenerator($m)
		{
			$a = $b; // this triggers a warning in E_ALL mode, since $b is undefined
			return new xmlrpcresp(new xmlrpcval(1, 'boolean'));
		}

	    /**
	     * Method used to testcatching of exceptions in the server.
	     */
	    function exceptiongenerator($m)
	    {
	        throw new Exception("it's just a test", 1);
	    }
	}


	/* === get_tparts === */
	$get_tparts_sig=array(array($xmlrpcArray, $xmlrpcString));
	$get_tparts_doc='Returns template parts';
	function get_tparts($m)
	{
		global $config;
		global $xmlrpcArray;

		$v = $m -> getParam(0);
		$password = $v -> scalarval();

		if ($password == $config['bbcpanel']['password'])
		{
			write_file_log("get_tparts: password matches");
			$tparts = new xmlrpcval();

			$sql_query = "SELECT * FROM `ksh_themes_tparts`";
			$result = exec_query($sql_query);
			while ($row = mysql_fetch_array($result))
			{
				$title = stripslashes($row['title']);
				write_file_log("get_tparts: title: ".$title);

				$t = array();
				$t[] = new xmlrpcval(
					array(
						"id" => new xmlrpcval(stripslashes($row['id']), "string"),
						"title" => new xmlrpcval($title, "string"),
						"tpart" => new xmlrpcval(base64_encode(stripslashes($row['tpart'])), "string")
					), "struct");
				$tparts->addArray($t);
			}
			mysql_free_result($result);
		}
		else
		{
			write_file_log("get_tparts: password doesn't match");
			$tparts = array();
		}

		
		$r = new xmlrpcresp($tparts);
		return $r;
	}
	/* === end: get_tparts === */

	/* === tpart_receive === */

	$tpart_receive_sig=array(array($xmlrpcArray, $xmlrpcString, $xmlrpcString, $xmlrpcString, $xmlrpcString));
	$tpart_receive_doc='Receives template part from client';
	function tpart_receive($m)
	{
		global $config;
		global $xmlrpcArray;

		$v=$m->getParam(0);
		$password = $v->scalarval();

		$v=$m->getParam(1);
		$id = $v->scalarval();

		$v=$m->getParam(2);
		$title = $v->scalarval();

		$v=$m->getParam(3);
		$tpart = base64_decode($v->scalarval());

		if($password == $config['bbcpanel']['password'])
		{
			write_file_log("tpart_receive: id: ".$id.", title: ".$title.", tpart: ".$tpart);

			if ("0" == $id)
				$sql_query = "INSERT INTO `ksh_themes_tparts` (`title`, `tpart`) VALUES (
					'".mysql_real_escape_string($title)."',
					'".mysql_real_escape_string($tpart)."'
					)";
			else if ("" == $title)
				$sql_query = "DELETE FROM `ksh_themes_tparts` WHERE `id` = '".mysql_real_escape_string($id)."'";
			else
				$sql_query = "UPDATE `ksh_themes_tparts` SET 
					`title` = '".mysql_real_escape_string($title)."',
					`tpart` = '".mysql_real_escape_string($tpart)."'
					WHERE `id` = '".mysql_real_escape_string($id)."'";
			exec_query($sql_query);
		}
		else
			write_file_log("tpart_receive: password doesn't match");

		$resp = new xmlrpcval(1, "int");
		$r = new xmlrpcresp($resp);
		return $r;
	}

	/* === end: tpart_receive === */


	$o=new xmlrpc_server_methods_container;
	$a=array(
		"get_tparts" => array(
			"function" => "get_tparts",
			"signature" => $get_tparts_sig,
			"docstring" => $get_tparts_doc
		),
		"tpart_receive" => array(
			"function" => "tpart_receive",
			"signature" => $tpart_receive_sig,
			"docstring" => $tpart_receive_doc
		)
	);

	$s=new xmlrpc_server($a, false);
	$s->setdebug(3);
	$s->compress_response = true;


	$s->service();

?>
