<?php

include_once("../../config.php");
ini_set('error_reporting', $config['base']['error_reporting']);
error_reporting($config['base']['error_reporting']);
if ($config['base']['error_reporting'])
	ini_set('display_errors', 1);
else
	ini_set('display_errors', 0);

include_once($config['base']['doc_root']."/modules/base/index.php");
include_once($config['base']['doc_root']."/modules/db/index.php");
include_once($config['base']['doc_root']."/modules/updater/index.php");
include_once($config['base']['doc_root']."/libs/xmlrpc/xmlrpc.inc");
include_once($config['base']['doc_root']."/libs/xmlrpc/xmlrpc_wrappers.inc");
include_once($config['base']['doc_root']."/libs/xmlrpc/xmlrpcs.inc");
connect_2db ($db_user, $db_password, $db_host, $db_name);


	/**
	* Used to test usage of object methods in dispatch maps and in wrapper code
	*/
	class xmlrpc_server_methods_container
	{
		/**
		* Method used to test logging of php warnings generated by user functions.
		*/
		function phpwarninggenerator($m)
		{
			$a = $b; // this triggers a warning in E_ALL mode, since $b is undefined
			return new xmlrpcresp(new xmlrpcval(1, 'boolean'));
		}

	    /**
	     * Method used to testcatching of exceptions in the server.
	     */
	    function exceptiongenerator($m)
	    {
	        throw new Exception("it's just a test", 1);
	    }
	}


	/* === update_all === */
	$update_all_sig=array(array($xmlrpcString, $xmlrpcString));
	$update_all_doc='Updates program code';
	function update_all($m)
	{
		global $config;
		global $user;

		$v = $m -> getParam(0);
		$password = base64_decode($v -> scalarval());

		if ($password == $config['bbcpanel']['password'])
		{
			write_file_log("update_all: password matches");
			$filename = $config['updater']['file_all'];
			$url = $config['updater']['url'].$filename;
			if (substr($_SERVER['DOCUMENT_ROOT'], -1) != "/")
				$doc_root = $_SERVER['DOCUMENT_ROOT']."/";
			else
				$doc_root = $_SERVER['DOCUMENT_ROOT'];
			$dl_path = $config['updater']['dl_path'];
			write_file_log("update_all: url: ".$url);
			write_file_log("update_all: dl_path: ".$dl_path);
			write_file_log("update_all: filename: ".$filename);
			write_file_log("update_all: doc_root: ".$doc_root);
			$result = updater_get_update($url, $doc_root.$dl_path.$filename, $doc_root);
			write_file_log("update_all: ".$result);
		}
		else
		{
			write_file_log("update_all: password doesn't match");
			$result = "Password doesn't match";
		}

		return new xmlrpcresp(new xmlrpcval($result, "string"));
	}
	/* === end: update_all === */



	$o=new xmlrpc_server_methods_container;
	$a=array(
		"update_all" => array(
			"function" => "update_all",
			"signature" => $update_all_sig,
			"docstring" => $update_all_doc
		)
	);

	$s=new xmlrpc_server($a, false);
	$s->setdebug(3);
	$s->compress_response = true;


	$s->service();

?>
